### ISSUE TITLE
[미션3] 중복 제거, clean code, 쿼리 보기 설정

### ISSUE THREAD

**Issue by eNoLJ** [bibi6666667/spring-boot-qna#4]
###  Job Description
> 작업 내용을 적어주세요

- [x] 개발 과정에서 발생한 중복 코드를 제거
- [x] SQL 쿼리를 볼 수 있도록 설정

### Todo
> 해당 작업이 완성되기 위해서 완료되어야 하는 작업 리스트를 적어주세요

- [x] 로그인한 유저인지, 세션은 올바르게 갖고 있는 것인지 확인하는 코드를 utils로 따로 관리
- [x] DB 관련 요청이 생기면 쿼리를 콘솔을 통해 볼 수 있도록 설정

### Status 관리
- Task Card 의 상태에 따라 To do, In progress, Done 유지를 해주세요
- 진행하던 Task Card 를 중간에 안하게 되는 경우, In Progress 에서 To do 로 Status 를 변경해 주시기 바랍니다.
