### ISSUE TITLE
[미션4] 회원과 질문간의 관계 매핑 및 생성일 추가

### ISSUE THREAD

**Issue by eNoLJ** [bibi6666667/spring-boot-qna#6]
###  Job Description
> 작업 내용을 적어주세요

- [ ] User와 Question 간의 관계를 매핑한다.
- [ ] Question에 생성일을 추가한다.

### Todo
> 해당 작업이 완성되기 위해서 완료되어야 하는 작업 리스트를 적어주세요

- [ ] Question의 writer를 User로 변경, 관계 매핑 설정
- [ ] Question을 생성할 때 생성일이 기록되도록 설정

### Status 관리
- Task Card 의 상태에 따라 To do, In progress, Done 유지를 해주세요
- 진행하던 Task Card 를 중간에 안하게 되는 경우, In Progress 에서 To do 로 Status 를 변경해 주시기 바랍니다.
